ci: attept to resolve disk space issues

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -56,31 +56,35 @@ jobs:
         permissions:
             checks: write
         steps:
-            # The fact that we even have to do this is absurd.
-            - name: Free disk space
-              if: matrix.os == 'ubuntu-latest'
-              run: |
-                  set -ex
-                  df -h
-                  sudo swapoff -a
-                  sudo rm -f /swapfile
-                  sudo apt clean
-                  docker rmi $(docker image ls -aq) || true
-                  sudo rm -rf \
-                    "$AGENT_TOOLSDIRECTORY" \
-                    /opt/google/chrome \
-                    /opt/microsoft/msedge \
-                    /opt/microsoft/powershell \
-                    /opt/pipx \
-                    /usr/lib/mono \
-                    /usr/local/julia* \
-                    /usr/local/lib/android \
-                    /usr/local/lib/node_modules \
-                    /usr/local/share/chromium \
-                    /usr/local/share/powershell \
-                    /usr/share/dotnet \
-                    /usr/share/swift
-                  df -h
+            # # The fact that we even have to do this is absurd.
+            # - name: Free disk space
+            #   if: matrix.os == 'ubuntu-latest'
+            #   run: |
+            #       sudo mkdir /mnt/target
+            #       sudo chown -R $(whoami) /mnt/target
+            #       sudo chmod -R u+rwx /mnt/target
+            #       echo "CARGO_TARGET_DIR=/mnt/target" >> $GITHUB_ENV
+            # set -ex
+            # df -h
+            # sudo swapoff -a
+            # sudo rm -f /swapfile
+            # sudo apt clean
+            # docker rmi $(docker image ls -aq) || true
+            # sudo rm -rf \
+            #   "$AGENT_TOOLSDIRECTORY" \
+            #   /opt/google/chrome \
+            #   /opt/microsoft/msedge \
+            #   /opt/microsoft/powershell \
+            #   /opt/pipx \
+            #   /usr/lib/mono \
+            #   /usr/local/julia* \
+            #   /usr/local/lib/android \
+            #   /usr/local/lib/node_modules \
+            #   /usr/local/share/chromium \
+            #   /usr/local/share/powershell \
+            #   /usr/share/dotnet \
+            #   /usr/share/swift
+            # df -h
 
             - name: Checkout source code
               uses: actions/checkout@v4
@@ -106,7 +110,9 @@ jobs:
 
             - name: Cargo test
               id: tests
-              run: cargo hack --feature-powerset --keep-going nextest run --no-fail-fast --workspace --exclude-features default
+              run: cargo nextest run --all-features --workspace
+              # XXX: Broken due to running out of disk space on GitHub CI
+              #run: cargo hack --feature-powerset --keep-going nextest run --no-fail-fast --workspace --exclude-features default
 
             # - name: Cargo test
             #   id: tests
@@ -161,34 +167,35 @@ jobs:
             - name: Run cargo clippy
               run: cargo hack --feature-powerset clippy --all-targets --exclude-features default -- -D warnings
 
-    coverage:
-        name: Report coverage
-        runs-on: ubuntu-latest
-        needs: [style, docs, test]
-        if: github.event_name != 'pull_request'
-        container:
-            image: xd009642/tarpaulin:develop-nightly
-            options: --security-opt seccomp=unconfined
+    # XXX: Disabled due to issues with GitHub CI disk space
+    # coverage:
+    #     name: Report coverage
+    #     runs-on: ubuntu-latest
+    #     needs: [style, docs, test]
+    #     if: github.event_name != 'pull_request'
+    #     container:
+    #         image: xd009642/tarpaulin:develop-nightly
+    #         options: --security-opt seccomp=unconfined
 
-        steps:
-            - name: Checkout repository
-              uses: actions/checkout@v4
+    #     steps:
+    #         - name: Checkout repository
+    #           uses: actions/checkout@v4
 
-            # XXX: container is missing 'jq' used by action
-            # - name: Cache the Cargo build files
-            #   uses: Leafwing-Studios/cargo-cache@v2
-            #   with:
-            #       cache-group: check
+    #         # XXX: container is missing 'jq' used by action
+    #         # - name: Cache the Cargo build files
+    #         #   uses: Leafwing-Studios/cargo-cache@v2
+    #         #   with:
+    #         #       cache-group: check
 
-            - name: Generate code coverage
-              run: |
-                  cargo +nightly tarpaulin --verbose --all-features --workspace --timeout 120 --out xml
+    #         - name: Generate code coverage
+    #           run: |
+    #               cargo +nightly tarpaulin --verbose --all-features --workspace --timeout 120 --out xml
 
-            - name: Upload coverage reports to Codecov
-              uses: codecov/codecov-action@v5
-              with:
-                  token: ${{ secrets.CODECOV_TOKEN }}
-                  fail_ci_if_error: true
+    #         - name: Upload coverage reports to Codecov
+    #           uses: codecov/codecov-action@v5
+    #           with:
+    #               token: ${{ secrets.CODECOV_TOKEN }}
+    #               fail_ci_if_error: true
 
     docs:
         name: Documentation
